### ISSUE TITLE
Cannot run train.py

### ISSUE THREAD

**Issue by Ardor-Wu** [MahdiShAhmadi/ReDMark#21]
(redmark) qilong3@madison:/scratch/qilong3/watermark_robustness/ReDMark$ python train.py
2024-04-16 15:45:55.103563: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-04-16 15:45:55.146928: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI AVX512_BF16 AVX512_FP16 AVX_VNNI AMX_TILE AMX_INT8 AMX_BF16 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-04-16 15:45:55.708777: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Loading dataset...
x_train shape: (333787, 32, 32, 1)
333787 train samples
2024-04-16 15:45:59.269301: W tensorflow/core/common_runtime/gpu/gpu_device.cc:2251] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
Traceback (most recent call last):
  File "/scratch/qilong3/watermark_robustness/ReDMark/train.py", line 151, in <module>
    encoder_model = conv2d_layer(num_of_filters, (2, 2), dilation_rate=1, activation='elu', padding='same', name='enc_conv2')(encoder_model)
  File "/scratch/qilong3/anaconda3/envs/redmark/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/scratch/qilong3/watermark_robustness/ReDMark/include/my_circular_layer.py", line 84, in build
    filter_shape=self.kernel.get_shape(),
AttributeError: 'Variable' object has no attribute 'get_shape'

The error message is shown above. I am using tensorflow 2.16.1 python 3.9 CUDA 12.2. Thanks!

**Comment by MahdiShAhmadi** [comment]
Hi Ardor-Wu, sorry for the late response. Were you able to resolve the issue?
